### ISSUE TITLE
urban38 mappoints 始终为0

### ISSUE THREAD

**Issue by darkdelting** [i2Nav-WHU/LE-VINS#1]
您好，很开心能看到这么棒的工作，请问为什么我用gvins的urban38.bag数据跑这个代码,keyframe , mappoints始终是0？是哪里配置的不对吗
![image](https://github.com/i2Nav-WHU/LE-VINS/assets/43160074/d490e7b9-49e5-4580-a13f-8b0c6da042b0)
并且这里的imu也是-9.8左右坐标轴是朝上的？ 这个gvins imu是不是需要调整下，调整后好像也有问题
![image](https://github.com/i2Nav-WHU/LE-VINS/assets/43160074/e9a240e1-2429-4524-afe6-c77b2c860670)

**Comment by thlsealight** [comment]
请使用[测试过的配置文件](https://github.com/i2Nav-WHU/LE-VINS/blob/main/config/le_vins_kaist.yaml)，测试gvins的urban38.bag和urban39.bag数据不需要修改代码。

**Comment by darkdelting** [comment]
确实正常了
![iikgeOD9ZL](https://github.com/i2Nav-WHU/LE-VINS/assets/43160074/f6da263a-f2f3-4657-9c72-c9074b1f32dc)
我看这里面主要是imu不一样，是不是r3live的数据集也得改imu参数，目前测试r3live的效果也不好，不知道有demo吗？

**Comment by thlsealight** [comment]
请查看LE-VINS目录下的config文件夹。
![image](https://github.com/i2Nav-WHU/LE-VINS/assets/26218386/17afe007-9efa-40d2-b00f-ee8aa68f806f)

**Comment by zhh2005757** [comment]
单靠相机和IMU就能把urban38跑成这个样子，我测试VINS-Fusion总会有飞掉的地方，很多时候是停车的时候，感觉就是动态物体太多了，只能说作者单靠IMU不需要加其他动态剔除算法就能做到鲁棒真厉害！

**Comment by 0456wrz** [comment]
可以请问一下这个urban38.bag数据集是下的IC-GVINs的吗？ 但是我看这个数据集的topic没有lidar的话题好像

**Comment by thlsealight** [comment]
> 可以请问一下这个urban38.bag数据集是下的IC-GVINs的吗？ 但是我看这个数据集的topic没有lidar的话题好像

LE-VINS可以跑纯VIO模式，LiDAR是可选的。
