### ISSUE TITLE
td的标定问题

### ISSUE THREAD

**Issue by JinMing-Gu** [i2Nav-WHU/LE-VINS#2]
感谢开源如此精彩的工作！

我观察到参数文件中有td_b_c、td_b_l等参数，请问(1)传感器之间存在时延的原因是什么，是因为各个传感器的时间戳并不能反映出其真实的采样时刻吗；(2)这些时间延迟参数是如何得到的，如果我想运行自己的数据集，该如何标定时间延迟参数，是否有论文或其他工作可以推荐一下？

感谢！

**Comment by thlsealight** [comment]
> 感谢开源如此精彩的工作！
> 
> 我观察到参数文件中有td_b_c、td_b_l等参数，请问(1)传感器之间存在时延的原因是什么，是因为各个传感器的时间戳并不能反映出其真实的采样时刻吗；(2)这些时间延迟参数是如何得到的，如果我想运行自己的数据集，该如何标定时间延迟参数，是否有论文或其他工作可以推荐一下？
> 
> 感谢！

时延往往是由于传感器时间不同步不准确造成的，可以说是时间戳不准确。对于相机和IMU的时延，Kalibr是可以直接标定出来的。如果没有准确的初始时延估计，建议设置为0，同时打开算法的时延在线估计功能，数据运行结束可以查看估计时延的情况。传感器时延估计的论文比较多，自行搜索一下吧。
